/**
 * Conecta Raros — Global Configuration
 * Overridden at runtime by /runtime-config.js (generated by Docker entrypoint)
 */
window.CR = window.CR || {};

CR.config = Object.assign({
    API_BASE_URL: 'https://social-care.acdgbrasil.com.br/api/v1',
    API_TOKEN: '',
    PAGE_SIZE: 20,
}, CR.config || {});
